name: Price Tracker Bot

on:
  schedule:
    # Every 15 minutes from 8:00 AM to 12:00 AM IST
    # UTC = IST - 5:30 → 2:00–18:59 UTC
    - cron: '*/15 2-18 * * *'
  workflow_dispatch: # allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Run Price Tracker Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          DATABASE: ${{ secrets.DATABASE }}
          COLLECTION: ${{ secrets.COLLECTION }}
          PRODUCT: ${{ secrets.PRODUCT }}
        run: python main.py
