name: Price Tracker Bot

on:
  schedule:
    # Runs every 15 minutes from 8:00 AM to 12:00 AM IST
    - cron: '0,15,30,45 2-18 * * *' 
  workflow_dispatch: # allows manual runs

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python main.py
